### ISSUE TITLE
Adjuster suggestion

### ISSUE THREAD

**Issue by HowardBaxton** [nPoseTeam/nPose-V4#3]
Suggestions made by Maureen Selene:
Add an option where we can set the adjuster gender by seat when they are rezzed.
Seat1=female, Seat2=male, etc.

Suggest changing the color of the animesh and floating text so each seat is a different color to make identification of the seat/adjuster easier to distinguish.

**Comment by LeonaMorro** [comment]
I also thought about something similar while programming the slave and adjuster part. I decided against it because there is an ongoing project ([LL Project Muscadine](https://community.secondlife.com/knowledgebase/english/project-muscadine-r1558/)) to implement "shapes" to animesh. Once this project is finished, there are a lot more things we have to think about. Until then I would suggest to not touch this and keep it simple.

**Comment by HowardBaxton** [comment]
I totally agree with your post.  I did however want to document the requests.  I am going to close this issue.  If it becomes important at a later time, it can be re-opened.
