### ISSUE TITLE
renaming some files

### ISSUE THREAD

**Issue by LeonaMorro** [nPoseTeam/nPose-V4#5]
a) I can't import the repo to my eclipse editor because of the colon ":" inside the utility cards name.
If you don't mind I would rename them back by replacing the ":" by a "."

b) Also I can't use my favorite editor (LSL Forge / Eclipse) with that *.lsl file ending. If you don't mind I would rename the scripts to *.lslp

**Comment by HowardBaxton** [comment]
I can do that.Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: LeonaMorro <notifications@github.com> Date: 5/13/20  8:39 AM  (GMT-07:00) To: nPoseTeam/nPose-V4 <nPose-V4@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [nPoseTeam/nPose-V4] renaming some files (#5) 
a) I can't import the repo to my eclipse editor because of the colon ":" inside the utility cards name.
If you don't mind I would rename them back by replacing the ":" by a "."
b) Also I can't use my favorite editor (LSL Forge / Eclipse) with that *.lsl file ending. If you don't mind I would rename the scripts to *.lslp

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/nPoseTeam/nPose-V4/issues/5",
"url": "https://github.com/nPoseTeam/nPose-V4/issues/5",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by LeonaMorro** [comment]
Thanks, Already done.
