### ISSUE TITLE
initial commit charset

### ISSUE THREAD

**Issue by LeonaMorro** [nPoseTeam/nPose-V4#6]
@HowardBaxton 
on your initial commit to this repo you didn't use the UTF-8 charset. That means that the special UTF-8 characters used in some scripts are lost. You can see it for example in the dialog script at the begin in the variables PAGE_FORWARD, PAGE_BACKWARD and so on. We have to make sure that each and every script is uploaded with the UTF-8 charset, because some scripts will not work otherwise.

**Comment by HowardBaxton** [comment]
Sorry, I didn't notice this.  I fixed the Dialog script and looked in the
others but didn't see any more.  Is this the only place the UTF-8
characters exist?

**Comment by LeonaMorro** [comment]
I compared the files from this repos with the last files on my computer:

Core: OK
The core contains UTF-8 chars inside the sanitizeString function but these are ok. There are some changes you made regarding gender and menuOnSit.

Dialog: ok
you made changes regarding macros

Menu: not ok
UTF-8 chars inside link_message num==PLUGIN_MENU and the function buildParamSet1

NC Reader: ok

Slave: ok

Admin HUD: not ok
not the latest version. The sound on pressing a button may not work in all cases.

nPose Adjuster: ?
there are 2 small changes . I guess you made them, but I'm not sure. I guess these changes will affect the positioning of adjusters rezzed more than 10m away from the nPose main object.


Since I'm already figured out the differences. I will update, the menu and the admin Hud script asap and then we should discuss the Adjuster changes

**Comment by HowardBaxton** [comment]
You are correct about the adjuster.  I was able to move the adjuster beyond 10 meters and change the position in the notecard just fine.  Everything worked fine until I tried to select that pose again with the adjusters rezzed.  It would not move past 10 meters and neither would the sitter.  I foune that the llSPPF would not move the adjuster past the 10 meter distance.   I left the rotation on the llSPPF but move the positioning to the old function used in V3.10.  This solved the problem.  I have also found that we are now limited to 1000 meter moves (even in old versions of nPose). I have in the past been able to move props and AV's 4000 meters up or down.  I assume this is a new limit in SL.Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: LeonaMorro <notifications@github.com> Date: 5/14/20  5:30 AM  (GMT-07:00) To: nPoseTeam/nPose-V4 <nPose-V4@noreply.github.com> Cc: HowardBaxton <howardbaxton@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [nPoseTeam/nPose-V4] initial commit charset (#6) 
I compared the files from this repos with the last files on my computer:
Core: OK
The core contains UTF-8 chars inside the sanitizeString function but these are ok. There are some changes you made regarding gender and menuOnSit.
Dialog: not ok
UTF-8 chars fixed but this is not the last version of the dialog script. I guess Maros will not work inside button names
Menu: not ok
UTF-8 chars inside link_message num==PLUGIN_MENU and the function buildParamSet1
NC Reader: ok
Slave: ok
Admin HUD: not ok
not the latest version. The sound on pressing a button may not work in all cases.
nPose Adjuster: ?
there are 2 small changes . I guess you made them, but I'm not sure. I guess these changes will affect the positioning of adjusters rezzed more than 10m away from the nPose main object.
Since I'm already figured out the differences. I will update the  dialog, the menu and the admin Hud script asap and then we should discuss the Adjuster changes

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/nPoseTeam/nPose-V4/issues/6#issuecomment-628572599",
"url": "https://github.com/nPoseTeam/nPose-V4/issues/6#issuecomment-628572599",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by LeonaMorro** [comment]
I see, that makes perfect sense.

But there is a second change you made (2-3 lines below that llSPPF).  You removed the line 
```lsl
llRegionSayTo(MyParentId, AdjusterChannel, addCommand("", ["AS_POS_ROT", MyCurrentNcPosition, MyCurrentNcRotation]));
```

I guess this could cause the bug mentioned in #1 ?

**Comment by HowardBaxton** [comment]
Correct, this is the fix for Issue # 1.  Editing the notecard would move
the adjuster but not the seated AV.  Sending back the new adjuster
position/rotation is to make sure the AV follows the new adjuster position.

Sorry to make you hunt down these changes.

**Comment by HowardBaxton** [comment]
closing this issue
